name: Scheduled City Website Deployer

on:
  # Runs once every hour, on the hour (e.g., 1:00, 2:00, 3:00)
  schedule:
    - cron: '0 * * * *'
  # Allows manual triggering for testing (without needing to enter a city)
  workflow_dispatch:

jobs:
  create-and-deploy-all-repos:
    runs-on: ubuntu-latest
    
    # Required permission settings for creating new repositories
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: 1. Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 2. Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 3. Install Required Python Libraries
      run: pip install PyGithub requests
      
    - name: 4. Run Script to Create & Deploy ALL Repos
      env:
        # Pass the secret token. No CITY_INPUT needed anymore.
        GH_TOKEN: ${{ secrets.websitemaker2 }}
        # Set the required delay between repo creations (in seconds)
        DEPLOY_DELAY: 180 
      run: python update_website.py
